---
meta_boxes:
  schools_metabox:
    id: general_mb
    title: Custom Fields
    object_types: 
      - post
      - page
    priority: high
    show_names: true
    context: normal
    fields: 
      shorter_title: 
        name: Shorter Title
        id: shorter_title
        type: text 
        desc: Some places in the theme require a short version of the title
  color_metabox:
    id: color_metabox
    title: Color
    object_types: 
      - term
    taxonomies: 
      - category
    fields: 
      testing: 
        name: Testing
        id: testing 
        type: text
        desc: testing